### ISSUE TITLE
Code not compiling

### ISSUE THREAD

**Issue by DukeAvi** [acmpesuecc/Shell#6]
Followed along the readme, code won't compile

```
shell.c:21:14: error: ‘shell_roll_wrapper’ undeclared here (not in a function)
   21 |     {"roll", shell_roll_wrapper, "Rolls the terminal. Usage: roll"}
```

**Comment by AmeyaKhanzode** [comment]
are you on windows?

**Comment by DukeAvi** [comment]
> are you on windows?

WSL

**Comment by AmeyaKhanzode** [comment]
send a screenshot of terminal

**Comment by DukeAvi** [comment]
![image](https://github.com/user-attachments/assets/eafb2dd7-d5c5-4dcd-9281-15a60f59845c)

**Comment by AmeyaKhanzode** [comment]
its working on mine

**Comment by AmeyaKhanzode** [comment]
sorry, i have fixed the code

**Comment by DukeAvi** [comment]
![image](https://github.com/user-attachments/assets/526ca52c-8c15-4c0b-8b1f-d4ff082bacdd)
issue persists

**Comment by Aanirudhh** [comment]
Can you assign me this issue
